name: Deploy Testing Branch

on:
  push:
    branches: 
      - testing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true

    - run: |
        # Clone the necessary repository and install dependencies
        git clone --depth=1 https://github.com/virtual-labs/ph3-lab-mgmt
        cd ph3-lab-mgmt
        npm install
        npm run build-exp
        cd ../

        # Set git user details for commits
        git config --local user.email "admin@vlabs.ac.in"
        git config --local user.name "vleadadmin"

        # Create an orphan gh-pages branch
        git checkout --orphan gh-pages
        git reset

        # Clean the destination folder (if exists)
        if [ -d "build/plugins" ]; then
          echo "Removing existing build/plugins directory to prevent conflicts"
          rm -rf build/plugins
        fi

        # Move build files to the root of the repository
        git add build/* -f
        git mv build/* ./ -f

        # Commit the changes
        git commit -m "Deploying experiment: https://virtual-labs.github.io/${{ github.repository }}"

    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ORG_OWNER_GITHUB_TOKEN }}
        force: true
        branch: gh-pages
